# MakeFile was generated by @mrtuxa

########################################################
####			GitHub								  ##
####	https://github.com/mrtuxa					  ##
########################################################


shell:
	gcc *.c -lreadline	
